"""Add fee_status and address column to student model

Revision ID: 06ccada2b575
Revises: f96d44d421db
Create Date: 2025-07-20 04:29:24.086366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ccada2b575'
down_revision: Union[str, Sequence[str], None] = 'f96d44d421db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('fee_status', sa.String(), nullable=True))
    op.add_column('students', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'address')
    op.drop_column('students', 'fee_status')
    # ### end Alembic commands ###
