"""Remove homeroom_class_id column from teachers model

Revision ID: 4376c1161162
Revises: 813dc87f5090
Create Date: 2025-07-25 01:26:46.421920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4376c1161162'
down_revision: Union[str, Sequence[str], None] = '813dc87f5090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_active_academic_year', table_name='academic_years', postgresql_where='(is_active = true)')
    op.drop_constraint('teachers_homeroom_class_id_fkey', 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'homeroom_class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('homeroom_class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('teachers_homeroom_class_id_fkey', 'teachers', 'classes', ['homeroom_class_id'], ['id'])
    op.create_index('unique_active_academic_year', 'academic_years', ['is_active'], unique=True, postgresql_where='(is_active = true)')
    # ### end Alembic commands ###
