"""Make academic_year_id NOT NULL

Revision ID: 64977c107f36
Revises: 0d9aee77cd35
Create Date: 2025-07-22 14:59:08.184522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64977c107f36'
down_revision: Union[str, Sequence[str], None] = '0d9aee77cd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'academic_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'academic_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
