"""Add class_subject_teacher table

Revision ID: 8666fe6610b7
Revises: 2a0c31c2ea45
Create Date: 2025-06-23 11:21:45.644676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8666fe6610b7"
down_revision: Union[str, Sequence[str], None] = "2a0c31c2ea45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_class_subject_teacher_id"),
        "class_subject_teacher",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_class_subject_teacher_id"), table_name="class_subject_teacher"
    )
    # ### end Alembic commands ###
