"""Updated students and class_subject_teacher

Revision ID: afb8ca58ef64
Revises: 80ac527a3df3
Create Date: 2025-07-23 10:29:47.821713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb8ca58ef64'
down_revision: Union[str, Sequence[str], None] = '80ac527a3df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('unique_active_academic_year', table_name='academic_years', postgresql_where='(is_active = true)')
    op.alter_column('class_subject_teacher', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('class_subject_teacher', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('class_subject_teacher', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_subject_teacher', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_subject_teacher', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_subject_teacher', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('unique_active_academic_year', 'academic_years', ['is_active'], unique=True, postgresql_where='(is_active = true)')
    # ### end Alembic commands ###
