"""Add gender and address to the teacher model

Revision ID: bd2d0c078f33
Revises: 06ccada2b575
Create Date: 2025-07-20 13:25:10.947025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd2d0c078f33'
down_revision: Union[str, Sequence[str], None] = '06ccada2b575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###

     # Backfill existing rows with default values
    op.execute(
        """
        UPDATE teachers
        SET gender = 'Unknown',
            address = 'Not Provided'
        WHERE gender IS NULL OR address IS NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'address')
    op.drop_column('teachers', 'gender')
    # ### end Alembic commands ###
