"""Add ON DELETE CASCADE to teachers.user_id

Revision ID: bfe21d0f0b71
Revises: 02f3162e2d1e
Create Date: 2025-07-02 23:06:42.210331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe21d0f0b71'
down_revision: Union[str, Sequence[str], None] = '02f3162e2d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teachers_user_id_fkey', 'teachers', type_='foreignkey')
    op.create_foreign_key('teachers_user_id_fkey', 'teachers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teachers_user_id_fkey', 'teachers', type_='foreignkey')
    op.create_foreign_key('teachers_user_id_fkey', 'teachers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
