"""Add missing FK indexes

Revision ID: f670cf776edf
Revises: 99d174158d2a
Create Date: 2025-07-25 16:53:04.447404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f670cf776edf'
down_revision: Union[str, Sequence[str], None] = '99d174158d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_class_subject_teacher_class_id'), 'class_subject_teacher', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_subject_teacher_subject_id'), 'class_subject_teacher', ['subject_id'], unique=False)
    op.create_index(op.f('ix_class_subject_teacher_teacher_id'), 'class_subject_teacher', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_results_academic_year_id'), 'results', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_results_student_id'), 'results', ['student_id'], unique=False)
    op.create_index(op.f('ix_results_subject_id'), 'results', ['subject_id'], unique=False)
    op.alter_column('students', 'fee_status',
               existing_type=postgresql.ENUM('Paid', 'Unpaid', 'Partial', name='feestatusenum'),
               nullable=False)
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.alter_column('students', 'fee_status',
               existing_type=postgresql.ENUM('Paid', 'Unpaid', 'Partial', name='feestatusenum'),
               nullable=True)
    op.drop_index(op.f('ix_results_subject_id'), table_name='results')
    op.drop_index(op.f('ix_results_student_id'), table_name='results')
    op.drop_index(op.f('ix_results_academic_year_id'), table_name='results')
    op.drop_index(op.f('ix_class_subject_teacher_teacher_id'), table_name='class_subject_teacher')
    op.drop_index(op.f('ix_class_subject_teacher_subject_id'), table_name='class_subject_teacher')
    op.drop_index(op.f('ix_class_subject_teacher_class_id'), table_name='class_subject_teacher')
    # ### end Alembic commands ###
