"""Make class name unique per academic year

Revision ID: 0d9aee77cd35
Revises: e9812cef77e4
Create Date: 2025-07-22 13:23:17.526217

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d9aee77cd35"
down_revision: Union[str, Sequence[str], None] = "e9812cef77e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("classes_name_key", "classes", type_="unique")
    op.create_unique_constraint(
        "uq_class_name_year", "classes", ["name", "academic_year_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_class_name_year", "classes", type_="unique")
    op.create_unique_constraint("classes_name_key", "classes", ["name"])
    # ### end Alembic commands ###
