"""added tenant foreign key to key models

Revision ID: 11153c8a74d4
Revises: 3a9999e6d54f
Create Date: 2025-08-07 23:53:39.950475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11153c8a74d4'
down_revision: Union[str, Sequence[str], None] = '3a9999e6d54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_years', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'academic_years', 'tenants', ['tenant_id'], ['id'])
    op.add_column('attendance', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.drop_index('ix_attendance_academic_year_id', table_name='attendance')
    op.drop_index('ix_attendance_class_id', table_name='attendance')
    op.drop_index('ix_attendance_date', table_name='attendance')
    op.drop_index('ix_attendance_id', table_name='attendance')
    op.drop_index('ix_attendance_marked_by', table_name='attendance')
    op.drop_index('ix_attendance_student_id', table_name='attendance')
    op.create_index(op.f('ix_attendance_academic_year_id'), 'attendance', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_attendance_class_id'), 'attendance', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendance_date'), 'attendance', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_marked_by'), 'attendance', ['marked_by'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendance_tenant_id'), 'attendance', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'attendance', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('class_subject_teacher', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_class_subject_teacher_tenant_id'), 'class_subject_teacher', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'class_subject_teacher', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('classes', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_classes_tenant_id'), 'classes', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'classes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('remarks', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_remarks_tenant_id'), 'remarks', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'remarks', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('results', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_results_tenant_id'), 'results', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'results', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('students', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'students', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('teachers', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_teachers_tenant_id'), 'teachers', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'teachers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_index(op.f('ix_teachers_tenant_id'), table_name='teachers')
    op.drop_column('teachers', 'tenant_id')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_tenant_id'), table_name='students')
    op.drop_column('students', 'tenant_id')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_index(op.f('ix_results_tenant_id'), table_name='results')
    op.drop_column('results', 'tenant_id')
    op.drop_constraint(None, 'remarks', type_='foreignkey')
    op.drop_index(op.f('ix_remarks_tenant_id'), table_name='remarks')
    op.drop_column('remarks', 'tenant_id')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_index(op.f('ix_classes_tenant_id'), table_name='classes')
    op.drop_column('classes', 'tenant_id')
    op.drop_constraint(None, 'class_subject_teacher', type_='foreignkey')
    op.drop_index(op.f('ix_class_subject_teacher_tenant_id'), table_name='class_subject_teacher')
    op.drop_column('class_subject_teacher', 'tenant_id')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_tenant_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_marked_by'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_date'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_class_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_academic_year_id'), table_name='attendance')
    op.create_index('ix_attendance_student_id', 'attendance', ['student_id'], unique=False)
    op.create_index('ix_attendance_marked_by', 'attendance', ['marked_by'], unique=False)
    op.create_index('ix_attendance_id', 'attendance', ['id'], unique=False)
    op.create_index('ix_attendance_date', 'attendance', ['date'], unique=False)
    op.create_index('ix_attendance_class_id', 'attendance', ['class_id'], unique=False)
    op.create_index('ix_attendance_academic_year_id', 'attendance', ['academic_year_id'], unique=False)
    op.drop_column('attendance', 'tenant_id')
    op.drop_constraint(None, 'academic_years', type_='foreignkey')
    op.drop_column('academic_years', 'tenant_id')
    # ### end Alembic commands ###
