"""Added tenant_id to subjects

Revision ID: 1b1a0e037b9f
Revises: 6e35fe576991
Create Date: 2025-08-09 20:14:39.477134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b1a0e037b9f"
down_revision: Union[str, Sequence[str], None] = "6e35fe576991"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subjects", sa.Column("tenant_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_subjects_tenant_id"), "subjects", ["tenant_id"], unique=False
    )
    op.create_foreign_key(
        None, "subjects", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subjects", type_="foreignkey")
    op.drop_index(op.f("ix_subjects_tenant_id"), table_name="subjects")
    op.drop_column("subjects", "tenant_id")
    # ### end Alembic commands ###
