"""Add AcademicYear model and link to Classes

Revision ID: 2222f57f44f1
Revises: 9cf18bdfbce6
Create Date: 2025-07-20 22:59:25.403180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2222f57f44f1"
down_revision: Union[str, Sequence[str], None] = "9cf18bdfbce6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_years",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_academic_years_id"), "academic_years", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_academic_years_name"), "academic_years", ["name"], unique=True
    )
    op.add_column("classes", sa.Column("academic_year_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "classes", "academic_years", ["academic_year_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "classes", type_="foreignkey")
    op.drop_column("classes", "academic_year_id")
    op.drop_index(op.f("ix_academic_years_name"), table_name="academic_years")
    op.drop_index(op.f("ix_academic_years_id"), table_name="academic_years")
    op.drop_table("academic_years")
    # ### end Alembic commands ###
