"""Add class_teacher_id column to Class

Revision ID: 301d1d615960
Revises: 5c09707f4d33
Create Date: 2025-07-12 04:43:41.777286

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "301d1d615960"
down_revision: Union[str, Sequence[str], None] = "5c09707f4d33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("classes", sa.Column("class_teacher_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "classes", "teachers", ["class_teacher_id"], ["id"])
    op.drop_constraint(
        "teachers_dedicated_class_id_fkey", "teachers", type_="foreignkey"
    )
    op.drop_column("teachers", "dedicated_class_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teachers",
        sa.Column(
            "dedicated_class_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "teachers_dedicated_class_id_fkey",
        "teachers",
        "classes",
        ["dedicated_class_id"],
        ["id"],
    )
    op.drop_constraint(None, "classes", type_="foreignkey")
    op.drop_column("classes", "class_teacher_id")
    # ### end Alembic commands ###
