"""Add contact, status, specialization, timestamps to teachers

Revision ID: 468f74927bdc
Revises: 7c896f76c2a0
Create Date: 2025-07-07 14:46:35.061493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "468f74927bdc"
down_revision: Union[str, Sequence[str], None] = "7c896f76c2a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teachers", sa.Column("contact", sa.String(), nullable=True))
    op.add_column("teachers", sa.Column("status", sa.String(), nullable=True))
    op.add_column("teachers", sa.Column("specialization", sa.String(), nullable=True))
    op.add_column(
        "teachers",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "teachers",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teachers", "updated_at")
    op.drop_column("teachers", "created_at")
    op.drop_column("teachers", "specialization")
    op.drop_column("teachers", "status")
    op.drop_column("teachers", "contact")
    # ### end Alembic commands ###
