"""resolve subject uniqueness per tenant

Revision ID: 4b776c348116
Revises: aefd21d97bbb
Create Date: 2025-09-01 00:31:43.332448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b776c348116"
down_revision: Union[str, Sequence[str], None] = "aefd21d97bbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_class_name_year", "classes", type_="unique")
    op.create_unique_constraint(
        "uq_class_tenant_name_year",
        "classes",
        ["tenant_id", "name", "academic_year_id"],
    )
    op.drop_constraint("subjects_name_key", "subjects", type_="unique")
    op.create_unique_constraint(
        "uq_tenant_subject_name", "subjects", ["tenant_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_tenant_subject_name", "subjects", type_="unique")
    op.create_unique_constraint("subjects_name_key", "subjects", ["name"])
    op.drop_constraint("uq_class_tenant_name_year", "classes", type_="unique")
    op.create_unique_constraint(
        "uq_class_name_year", "classes", ["name", "academic_year_id"]
    )
    # ### end Alembic commands ###
