"""Switch dedicated_class FK to Teacher

Revision ID: 5c09707f4d33
Revises: 468f74927bdc
Create Date: 2025-07-12 03:50:17.168640

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c09707f4d33"
down_revision: Union[str, Sequence[str], None] = "468f74927bdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("classes_class_teacher_id_fkey", "classes", type_="foreignkey")
    op.drop_column("classes", "class_teacher_id")
    op.add_column(
        "teachers", sa.Column("dedicated_class_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "teachers", "classes", ["dedicated_class_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teachers", type_="foreignkey")
    op.drop_column("teachers", "dedicated_class_id")
    op.add_column(
        "classes",
        sa.Column("class_teacher_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "classes_class_teacher_id_fkey",
        "classes",
        "teachers",
        ["class_teacher_id"],
        ["id"],
    )
    # ### end Alembic commands ###
