"""Set tenant_id to not null across all tables

Revision ID: 6e35fe576991
Revises: 11153c8a74d4
Create Date: 2025-08-08 19:23:56.046621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e35fe576991"
down_revision: Union[str, Sequence[str], None] = "11153c8a74d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "academic_years", "tenant_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column("attendance", "tenant_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "class_subject_teacher", "tenant_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column("classes", "tenant_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("remarks", "tenant_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("results", "tenant_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("students", "tenant_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("teachers", "tenant_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("users", "tenant_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "tenant_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("teachers", "tenant_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("students", "tenant_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("results", "tenant_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("remarks", "tenant_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("classes", "tenant_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "class_subject_teacher", "tenant_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column("attendance", "tenant_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "academic_years", "tenant_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
