"""Add is_archived column to subjects model

Revision ID: 71f67f894aff
Revises: 727dd16b78cc
Create Date: 2025-07-25 19:17:26.236799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71f67f894aff"
down_revision: Union[str, Sequence[str], None] = "727dd16b78cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema safely."""

    # FK fixes
    op.drop_constraint("classes_class_teacher_id_fkey", "classes", type_="foreignkey")
    op.create_foreign_key(
        None, "classes", "teachers", ["class_teacher_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint("remarks_teacher_id_fkey", "remarks", type_="foreignkey")
    op.create_foreign_key(
        None, "remarks", "teachers", ["teacher_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint("results_subject_id_fkey", "results", type_="foreignkey")
    op.create_foreign_key(
        None, "results", "subjects", ["subject_id"], ["id"], ondelete="SET NULL"
    )

    # ✅ 1: Add column, nullable=True
    op.add_column("subjects", sa.Column("is_archived", sa.Boolean(), nullable=True))

    # ✅ 2: Backfill
    op.execute("UPDATE subjects SET is_archived = FALSE")

    # ✅ 3: Alter to NOT NULL
    op.alter_column("subjects", "is_archived", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subjects", "is_archived")
    op.drop_constraint(None, "results", type_="foreignkey")
    op.create_foreign_key(
        "results_subject_id_fkey", "results", "subjects", ["subject_id"], ["id"]
    )
    op.drop_constraint(None, "remarks", type_="foreignkey")
    op.create_foreign_key(
        "remarks_teacher_id_fkey", "remarks", "teachers", ["teacher_id"], ["id"]
    )
    op.drop_constraint(None, "classes", type_="foreignkey")
    op.create_foreign_key(
        "classes_class_teacher_id_fkey",
        "classes",
        "teachers",
        ["class_teacher_id"],
        ["id"],
    )
    # ### end Alembic commands ###
