"""Rename teacher_id to class_teacher_id in classes table

Revision ID: 7c896f76c2a0
Revises: bfe21d0f0b71
Create Date: 2025-07-03 00:22:35.104535

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c896f76c2a0"
down_revision: Union[str, Sequence[str], None] = "bfe21d0f0b71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("classes", sa.Column("class_teacher_id", sa.Integer(), nullable=True))
    op.drop_constraint("classes_teacher_id_fkey", "classes", type_="foreignkey")
    op.create_foreign_key(None, "classes", "teachers", ["class_teacher_id"], ["id"])
    op.drop_column("classes", "teacher_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classes",
        sa.Column("teacher_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "classes", type_="foreignkey")
    op.create_foreign_key(
        "classes_teacher_id_fkey", "classes", "teachers", ["teacher_id"], ["id"]
    )
    op.drop_column("classes", "class_teacher_id")
    # ### end Alembic commands ###
