"""Add homeroom_class_id to teachers

Revision ID: 80ac527a3df3
Revises: 5c1146ae5e22
Create Date: 2025-07-23 01:10:05.786275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80ac527a3df3"
down_revision: Union[str, Sequence[str], None] = "5c1146ae5e22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('unique_active_academic_year', table_name='academic_years', postgresql_where='(is_active = true)')
    op.add_column(
        "teachers", sa.Column("homeroom_class_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "teachers", "classes", ["homeroom_class_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teachers", type_="foreignkey")
    op.drop_column("teachers", "homeroom_class_id")
    op.create_index(
        "unique_active_academic_year",
        "academic_years",
        ["is_active"],
        unique=True,
        postgresql_where="(is_active = true)",
    )
    # ### end Alembic commands ###
