"""Add guardian_contact to students

Revision ID: 97f4fe39fc08
Revises: f4ebd914610a
Create Date: 2025-07-19 13:19:51.327737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97f4fe39fc08"
down_revision: Union[str, Sequence[str], None] = "f4ebd914610a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("guardian_contact", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "guardian_contact")
    # ### end Alembic commands ###
