"""Add created_at and updated_at to subject model

Revision ID: 9cf18bdfbce6
Revises: b213f094d029
Create Date: 2025-07-20 16:40:18.782748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9cf18bdfbce6"
down_revision: Union[str, Sequence[str], None] = "b213f094d029"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjects",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "subjects",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###

    # Backfill all rows with the current timestamp
    op.execute(
        """
        UPDATE subjects
        SET created_at = NOW(),
            updated_at = NOW(),
        WHERE created_at IS NULL OR updated_at IS NULL
    """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subjects", "updated_at")
    op.drop_column("subjects", "created_at")
    # ### end Alembic commands ###
