"""add tenant_id to academic_years

Revision ID: aefd21d97bbb
Revises: f20c714151b6
Create Date: 2025-08-26 22:16:24.401237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aefd21d97bbb"
down_revision: Union[str, Sequence[str], None] = "f20c714151b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_academic_years_name", table_name="academic_years")
    op.create_index(
        op.f("ix_academic_years_name"), "academic_years", ["name"], unique=False
    )
    op.create_unique_constraint(
        "uq_academic_year_name_tenant", "academic_years", ["name", "tenant_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_academic_year_name_tenant", "academic_years", type_="unique")
    op.drop_index(op.f("ix_academic_years_name"), table_name="academic_years")
    op.create_index("ix_academic_years_name", "academic_years", ["name"], unique=True)
    # ### end Alembic commands ###
