"""Update class model

Revision ID: d973b8c44773
Revises: 51be2f131ef8
Create Date: 2025-07-25 20:31:10.754454

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d973b8c44773"
down_revision: Union[str, Sequence[str], None] = "51be2f131ef8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("remarks_result_id_fkey", "remarks", type_="foreignkey")
    op.create_foreign_key(
        None, "remarks", "results", ["result_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "remarks", type_="foreignkey")
    op.create_foreign_key(
        "remarks_result_id_fkey", "remarks", "results", ["result_id"], ["id"]
    )
    # ### end Alembic commands ###
