"""Add created_at and updated_at to classes

Revision ID: f4ebd914610a
Revises: 301d1d615960
Create Date: 2025-07-16 01:24:43.701932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4ebd914610a"
down_revision: Union[str, Sequence[str], None] = "301d1d615960"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classes",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "classes",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###

    # ✅ Backfill old rows (PostgreSQL only)
    op.execute(
        "UPDATE classes SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL;"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classes", "updated_at")
    op.drop_column("classes", "created_at")
    # ### end Alembic commands ###
